### ISSUE TITLE
Memory leak on page with many event dispatches

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/web-vitals#551] opened 2024-10-18 17:16 UTC
Related DevTools bug: b/369633243

1. Open DevTools
2. Go to Settings > Experiments and make sure the "Performance panel: enable live metrics landing page" experiment is *disabled*
	- 	This is to ensure the web-vitals.js code shipped with DevTools is not injected
4. Reload DevTools
5. Open the DevTools Performance monitor and check "JS event listeners"
6. Go to the following page and click the button:
```html
<!DOCTYPE HTML>
<script type="module">
  import {onCLS, onINP, onLCP} from 'https://unpkg.com/web-vitals@4?module';

  // Edit: onCLS and onINP don't appear to cause any memory leaks
  // onCLS(console.log);
  // onINP(console.log);
  onLCP(console.log);
</script>
<script>
function spamEvents() {
  for (let i = 0; i < 10_000; i++) {
    // Cannot be GC'd until page reload
    document.dispatchEvent(new MouseEvent('click', {
      view: window,
      clientX: 0,
      clientY: 0
    }));

    // Cannot be GC'd until page reload
    document.dispatchEvent(new MouseEvent('click', {
      view: null,
      clientX: 0,
      clientY: 0
    }));

    // Can be GC'd
    document.dispatchEvent(new MouseEvent('mousedown', {
      view: window,
      clientX: 0,
      clientY: 0
    }));

    // Cannot be GC'd until page reload
    document.dispatchEvent(new KeyboardEvent('keydown', {
      key: 'Enter'
    }));

    // Can be GC'd
    document.dispatchEvent(new KeyboardEvent('keyup', {
      key: 'Enter'
    }));

    // Can be GC'd - (deprecated)
    document.dispatchEvent(new KeyboardEvent('keypress', {
      key: 'Enter'
    }));
  }
}

function round_a_bit(v) {
  // Useful to get garbage off the end of a value that originally came from a 32-bit float.
  return Math.round(v * 10000) / 10000.0;
}

function run() {
  let start = performance.now();
  spamEvents();
  let end = performance.now();
  document.getElementById("output").append(round_a_bit(end - start) + "ms\n");
}
</script>
<input type=button onclick="run()" value=Run>
<pre id="output"></pre>
```

**Expected**

(result achieved by removing web-vitals code from the field above)

<img width="1015" alt="Screenshot 2024-10-18 at 10 12 59 AM" src="https://github.com/user-attachments/assets/80aec482-9bb7-48ed-be1f-6c2c43b80158">

**Actual**

<img width="1015" alt="Screenshot 2024-10-18 at 10 13 41 AM" src="https://github.com/user-attachments/assets/b4b7c960-1388-4433-beed-7ffb665ec763">

**Comment by adamraine** [comment] 2024-10-18 17:37
I think I tracked it down to this code in `onLCP`:

https://github.com/GoogleChrome/web-vitals/blob/9b932519b16f72328c6d8e9814b811f1bc1a0bb5/src/onLCP.ts#L100-L108

Disabling this code will prevent the memory leak.

**Comment by tunetheweb** [comment] 2024-10-18 18:25
Think this is a dupe of #534? It's fixed in v5 which is currently in beta.

**Comment by tunetheweb** [comment] 2024-10-18 18:27
@philipwalton maybe we should consider a final v4 branch with this fix?

**Comment by philipwalton** [comment] 2024-10-18 18:57
> @philipwalton maybe we should consider a final v4 branch with this fix?

Did you mean to say v4?

**Comment by tunetheweb** [comment] 2024-10-18 18:59
Yes. For those that don’t want to upgrade to v5 (at least right away) for FID or older browser build reasons.

Then again, not had many complaints about this and Adam’s example is an extreme example.

**Comment by philipwalton** [comment] 2024-10-18 19:13
The base branches for these are very different, so we wouldn't be able to just cherry-pick that commit into v4, but it would be simple enough add `{once:true, capture:true}` to the `addEventListener()` call.

**Comment by adamraine** [comment] 2024-10-22 18:56
I'm having difficulty rolling `5.0.0-rc.0` into DevTools (possibly an issue with DevTools still investigating) so I think a minor version bump with the changes @philipwalton mentioned would help out a bit here.

**Comment by tunetheweb** [comment] 2024-10-22 19:01
Yeah I think that makes sense too. Raised #554 for that.

Also super curious to hear about your v5 RC issues—ideally before we finalise that.

**Closed** 2024-10-22 19:08 UTC
