### ISSUE TITLE
performance.getEntriesByName is not a function. (In 'performance.getEntriesByName("first-contentful-paint")', 'performance.getEntriesByName' is undefined

### ISSUE THREAD

**Issue by huanghairong2312** [GoogleChrome/web-vitals#174] opened 2021-08-05 07:13 UTC
performance.getEntriesByName is not a function. (In 'performance.getEntriesByName("first-contentful-paint")', 'performance.getEntriesByName' is undefined  .

in webvitals/getFCP.js
device: Iphone 
webvitals version：1.1.2

**Comment by philipwalton** [comment] 2021-08-05 14:33
This is a duplicate of https://github.com/GoogleChrome/web-vitals/issues/172. In short, upgrading to version 2.0.1 of greater should fix the issue.

**Closed by philipwalton** 2021-08-05 14:33 UTC
