### ISSUE TITLE
CLS recording "expected layout shifts"

### ISSUE THREAD

**Issue by pheavey** [GoogleChrome/web-vitals#91] opened 2020-11-17 23:03 UTC
We have implemented Web Vitals code for our client, on amerigas.com.  In our pre-production testing, we found an issue with the CLS metric.  CLS is supposed to be set on “unexpected layout shifts” on the page, but is being set on “expected” layout shifts, including those listed below:

- The Alert header opening and closing;
- Closing FAQ sliders;
- The sticky header “sticking” and “unsticking”;
- Opening a new browser tab and returning to the page (this appears to happen only on Macs);
- Chrome autofill values being displayed after cursor focus on a form field.

This is artificially inflating the CLS metric for our client, and we are concerned that this will negatively affect our client's Web Vitals score and SEO.

**Comment by philipwalton** [comment] 2020-11-17 23:58
Can you provide more details? It's not clear to me whether the examples in this list involve user interactions. If they do, can you please explain exactly what the user interaction was?

Also, in case you're not aware, the interactions used to consider a shift "expect" are tap, click, and keypress. See [this callout on web.dev/cls](https://web.dev/cls/#expected-vs.-unexpected-layout-shifts):

> The `hadRecentInput` flag will only be true for discrete input events like tap, click, or keypress. Continuous interactions such as scrolls, drags, or pinch and zoom gestures are not considered "recent input". See the [Layout Instability Spec](https://github.com/WICG/layout-instability#recent-input-exclusion) for more details.

**Comment by pheavey** [comment] 2020-11-18 18:51
Philip,

Thanks for the reply.  What I noted are interactions, explained below, and can be replicated on [this page](https://www.amerigas.com/support/accounts), among others.  In testing the Web Vitals code, we had the values set in console.log, and saw that CLS was set on each of these actions.

- Closing FAQ sliders - click on FAQ to open, then click to close
- The sticky header “sticking” and “unsticking” - scroll up and down the page; also, open a meu drop down (e.g., About Propane) and scroll down the page
- Chrome autofill values being displayed after cursor focus on a form field - place cursor in the Search All Support box with autofill turned on

**Comment by philipwalton** [comment] 2020-11-19 01:13
> * Closing FAQ sliders - click on FAQ to open, then click to close

I think in this case the API is functioning correctly. The problem here is that the animation is too slow, so the shifts happening more than 500ms after the user clicks are in fact being reported as "unexpected".

See my console output, and notice the `hadRecentInput` flags:

<img width="1291" alt="Screen Shot 2020-11-18 at 5 07 04 PM" src="https://user-images.githubusercontent.com/326742/99607430-a72aed00-29c0-11eb-840a-e109abe87513.png">

To fix this, you have two options:

1) Switch to only transitioning the `transform` property (recommended in general).
2) Make the transition faster.

Honestly, in my opinion I'd recommend doing both. The first part of the transition does feel a bit slow to me.

> * The sticky header “sticking” and “unsticking” - scroll up and down the page; also, open a meu drop down (e.g., About Propane) and scroll down the page

Hmm, this looks like it might be a bug in Chrome. Interestingly, we had another report today for what looks to be the same issue. Here's the crbug to track it:
https://bugs.chromium.org/p/chromium/issues/detail?id=1150657

> * Chrome autofill values being displayed after cursor focus on a form field - place cursor in the Search All Support box with autofill turned on

I can't actually reproduce this issue, as no autofilling is happening for me.

* * *

I'm going to close this issue as I think none of the things reported are a problem with the `web-vitals` library, but rather concerns with the Web APIs. If you feel strongly that these APIs are affecting the metric quality, I'd recommend filing CR bugs (crbug.com) to report the issues rather than reporting them here.

**Closed by philipwalton** 2020-11-19 01:13 UTC
