### ISSUE TITLE
Google Ads report into Analytics impacted by Web Vitals

### ISSUE THREAD

**Issue by ubertu** [GoogleChrome/web-vitals#74] opened 2020-10-01 11:52 UTC
Hi all, we added web-vitals project in our web side to keep track of new measures. We are used to use Google Analytics as well to follow lot of metrics and during our checks we discovered a strange and huge increments on Users (and a lot less on Sessions) in Google Ads reports on GA. We found that the increment is due to a series of hits without a campaignId. The increments are started when we published web vitals tag through Tag Manager.
Some considerations we did (hope to be correct on that):

- GA Google Ads report is based on Source (google) and medium (cpc)
- the (huge) difference between users and sessions in report is due to the fact web vitals are NON interactive events, instead the session exposed in the report are the interactive one.
- source and medium are correct, they are set in the session, simply, it seems to me that every web vitals hits impact the Google Ads report as well.

Any idea on how to prevent this behaviour?

**Comment by philipwalton** [comment] 2020-10-02 22:31
Hmmm, I'm not familiar with the Google Ads report, but using this library with analytics.js or gtag.js as describe in the documentation should not have any affect on your user count. It *could* have an affect on your session count, if the user stays on your page for a really long time and your page continues to have layout shifts after the session has timed out.

> - the (huge) difference between users and sessions in report is due to the fact web vitals are NON interactive events, instead the session exposed in the report are the interactive one.

The use of non-interactive event is intentional. *Not* doing this would lead to a significant (and likely undesirable) reduction in bounce rate.

I can't speak to how non interactive events affect the Google Ads report, as I said I'm not familiar with that report.

**Comment by ubertu** [comment] 2020-10-05 15:23
for what I can understand, the "issue" in the report is due to fact every web vitals event is recognized as an hit (correct) by analytics and every hit inherits from also the channel (source and medium), so it actually affect that report.. I'm wondering if change the property, having a single one for web vitals, can be a solution

**Comment by philipwalton** [comment] 2020-10-22 01:44
I suspect the issue is due to an incorrect implementation of Google Analytics and not an issue caused by this library. Without more information, though, it's impossible to say for sure. I'm going to close this issue, but If you get more information, please feel free to reply here.

**Closed by philipwalton** 2020-10-22 01:44 UTC

**Comment by adaolima** [comment] 2021-01-15 11:50
It's happened the same with me, using nuxt-community/web-vitals-module. 
After added web-vitals, happening a huge increments on Users, and decrements on Sessions, as can see on the link. (Users: Dark Blue, Sessions: Light Blue) [https://drive.google.com/file/d/14iTycoDABZL79olWkzLEU7v-fIK9L0Tt/view?usp=sharing](https://drive.google.com/file/d/14iTycoDABZL79olWkzLEU7v-fIK9L0Tt/view?usp=sharing)
After, deactivated web-vitals, all came back to normal.

**Comment by philipwalton** [comment] 2021-01-20 05:31
If anyone experiencing this issue could send me the details of their configuration, I'd be happy to take a look, but this behavior has not happened for any of the accounts I manage, so I continue to suspect it's an issue of incorrect implementation.
