### ISSUE TITLE
Pages marked as "need an improvement"

### ISSUE THREAD

**Issue by mdromed** [GoogleChrome/web-vitals#173] opened 2021-08-02 19:33 UTC
Hello dear @philipwalton 
Can you help me with this issue?  [https://github.com/GoogleChrome/web.dev/issues/5829](url)
Every product page gets very good result  in [https://developers.google.com/speed/pagespeed/insights/](url), however in google search console they are marked as "needs an improvement"

website is https://www.be be mo vil.com (without spaces of course)
Please access and click over any item to enter product page and to can check that url on Pagespeed insights.
For example:  "https://www.be be mo vil.com/kinderkraft-prime-3-en-1-carrito-bebe-trio-3-piezas-id559"
When you can please help me if it is possible.... i dont know what to do :(

Best Regards

**Comment by mdromed** [comment] 2021-08-03 17:47
Can you help me dear @philipwalton?

**Comment by philipwalton** [comment] 2021-08-05 00:25
Hi @mdromed, the issues in this repo are meant to be for things specific to the web-vitals JavaScript library and not Web Vitals questions in general, so I'm going to close this issue, but I'll offer some suggestions that should hopefully help you.

First, of all, it does look like there are CLS issues on your site, as you can see in this screenshot (taken from [this report](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.bebemovil.com&tab=mobile)):

<img width="892" alt="Screen Shot 2021-08-04 at 5 18 12 PM" src="https://user-images.githubusercontent.com/326742/128271975-df1e4d4d-1b96-405e-ab2d-a0655819fb46.png">

I see in the other issue you mentioned that your PSI score is 98 or 100. I know this can be confusing, but [that score is your Lighthouse score](https://developers.google.com/speed/docs/insights/v5/about#score) and does not have anything to do with your [field data](https://web.dev/user-centric-performance-metrics/#in-the-field), which is what Core Web Vitals are based on.

I understand that this can be confusing since the tool shows both, and I'm working with the team that builds PSI to make the difference clearer.

If you want to better understand what is causing a CLS of 0.12 in your field data, I recommend reading this post: [Debug Web Vitals in the field](https://web.dev/debug-web-vitals-in-the-field/)

**Closed by philipwalton** 2021-08-05 00:25 UTC

**Comment by mdromed** [comment] 2021-08-05 01:00
Hi.
Thank you very much for your response.
Then truly it is very confusing :(

The strange thing is that my average CLS score is not good, because on every test i run CLS is always good (green).
I dont understand it.

Also, some weeks ago, 100% of my web pages were considered as fast by Google Search Console Tool and User experience  metrics (can you see capture i uploaded to the post) and suddenly % goes to 0... my code was the same! :(

I am really confused on about it




El 5 de agosto de 2021 2:25:33 CEST, Philip Walton ***@***.***> escribió:
Hi @mdromed, the issues in this repo are meant to be for things specific to the web-vitals JavaScript library and not Web Vitals questions in general, so I'm going to close this issue, but I'll offer some suggestions that should hopefully help you.

First, of all, it does look like there are CLS issues on your site, as you can see in this screenshot (taken from [this report](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.bebemovil.com&tab=mobile)):

<img width="892" alt="Screen Shot 2021-08-04 at 5 18 12 PM" src="https://user-images.githubusercontent.com/326742/128271975-df1e4d4d-1b96-405e-ab2d-a0655819fb46.png">

I see in the other issue you mentioned that your PSI score is 98 or 100. I know this can be confusing, but [that score is your Lighthouse score](https://developers.google.com/speed/docs/insights/v5/about#score) and does not have anything to do with your [field data](https://web.dev/user-centric-performance-metrics/#in-the-field), which is what Core Web Vitals are based on.

I understand that this can be confusing since the tool shows both, and I'm working with the team that builds PSI to make the difference clearer.

If you want to better understand what is causing a CLS of 0.12 in your field data, I recommend reading this post: [Debug Web Vitals in the field](https://web.dev/debug-web-vitals-in-the-field/)







-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/GoogleChrome/web-vitals/issues/173#issuecomment-893068596

mdromed

**Comment by rviscomi** [comment] 2021-08-05 01:09
@mdromed you might find this post useful to more realistically simulate CLS issues in lab tooling: https://dev.to/rick_viscomi/simulating-real-users-in-the-lab-to-debug-cls-issues-3hnp

**Comment by mdromed** [comment] 2021-08-05 01:30
ok, i will try that tool asap.
Thank you very much

El 5 de agosto de 2021 3:09:47 CEST, Rick Viscomi ***@***.***> escribió:
@mdromed you might find this post useful to more realistically simulate CLS issues in lab tooling: https://dev.to/rick_viscomi/simulating-real-users-in-the-lab-to-debug-cls-issues-3hnp

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/GoogleChrome/web-vitals/issues/173#issuecomment-893085013

mdromed

**Comment by mdromed** [comment] 2021-08-10 18:56
Excuse me again dear @philipwalton but if you can apreciate the CLS value got from PSI test of homepage of "https://www.bebe movil.com" (without spaces), you will see that CLS result is 0 for that page, even though average CLS of site is 0,14.
I think there is a wrong thing in metric system because all my pages give me a CLS value under 0,1, however Google Search Console keep indicating that they are slow or need an improvement.

see this capture please:  https://ibb.co/8zQmKmY

Thanks so much in advance

**Comment by rviscomi** [comment] 2021-08-10 20:21
@mdromed if you switch to the Desktop tab, PSI's lab data does report some layout stability issues: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.bebemovil.com&tab=desktop

![image](https://user-images.githubusercontent.com/1120896/128929308-cbdaa4e3-4d5c-401d-a2c2-9a67b02d5262.png)

![image](https://user-images.githubusercontent.com/1120896/128929348-958b34fd-d123-493d-aca0-4196884d987b.png)

Fixing the issues in the desktop test will probably also help your mobile scores.

**Comment by mdromed** [comment] 2021-08-10 23:03
Thank you for your reply @rviscomi but it only gets bad score sometimes... not always. Maybe 1 of each 10 tests it gets bad score.
Please can you repeat the test 1 or 2 more times? You will can what i say.
I wait for your answer.
;)

**Comment by mdromed** [comment] 2021-08-10 23:31
If i load the url into a VPN, CLS score gets worse.
How ever i dont understand why CLS is so bad, cause i have tested like a 
human visitor and content doesnt make any movement...  design is still 
fixed.....
Please see this captures from my last PSI test....

I use deferer javascript (after onload event) to load all elements of 
the main list of products to dont break the html design estructure.
I dont understand why my CLS desktop scoring is so bad.
PLEASE HELP ME

**Comment by rviscomi** [comment] 2021-08-10 23:45
The fact that we're able to reproduce CLS issues (even some of the time) means that real users are also experiencing these issues, which is negatively affecting your CWV scores. I'd recommend reviewing the guidance in the newly published [CWV tooling workflow doc](https://web.dev/vitals-tools-workflow/#step-b:-debug-and-optimize) to help you debug and optimize CLS.

Also as @philipwalton mentioned, this GitHub repository is not intended for general Web Vitals questions, so I'd recommend reviewing the docs and opening a thread at https://groups.google.com/g/web-vitals-feedback if you run into any more issues.

**Comment by mdromed** [comment] 2021-08-10 23:48
Thank you for your help but i really dont know how to debug it if only 
fails some times.

:(
