### ISSUE TITLE
Expose ability to reset internal state of metrics (specifically INP)

### ISSUE THREAD

**Issue by srubin** [GoogleChrome/web-vitals#461] opened 2024-04-10 16:05 UTC
We are using this library to track INP in a large single page app. Sessions with the app can be long -- sometimes hours. We are interested in collecting INP over a smaller time range, rather than for an entire session. The docs indicate that it's [important to track changes to INP over time,](https://github.com/GoogleChrome/web-vitals?tab=readme-ov-file#oninp) but INP as reported by this library is only ever increasing. So, it doesn't reflect the experience that a user is having for a given, say, 10 minute span of a session.

I was wondering if there has been any thought about exposing a function that resets the internal state for a given metric. I can fork the library and implement what I need for our use case [(e.g., it seems like this might be close to the behavior we need)](https://github.com/GoogleChrome/web-vitals/blob/73c9f0de5b4f3fa25a79cd39006a082be0c5d952/src/onINP.ts#L243-L258), but I'm wondering if others have run into this, or if there's something I'm missing about my understanding of the library and its best practices.

**Comment by tunetheweb** [comment] 2024-04-13 16:39
Duplicate of #448

**Closed** 2024-04-15 22:21 UTC
