### ISSUE TITLE
v3.3.2 throw error in IE9.

### ISSUE THREAD

**Issue by laoboxie** [GoogleChrome/web-vitals#350] opened 2023-06-02 08:00 UTC
web-vitals@3.3.2 throw error in IE9.
The error is caused by performance.now()
lib: https://unpkg.com/web-vitals@3.3.2/dist/web-vitals.iife.js

images:
![image](https://github.com/GoogleChrome/web-vitals/assets/23701019/c4d97026-8ad2-4ee3-9fde-2cdfe9601214)
![image](https://github.com/GoogleChrome/web-vitals/assets/23701019/39c73bad-fb04-4f90-a6a9-919eeb02c1c0)

**Comment by philipwalton** [comment] 2023-06-16 06:19
I can't reproduce this error when testing on IE9 via browserstack.com. @laoboxie can you clarify exactly what code you're running that's causing this error?

I'm trying the following, which doesn't error for me in IE9.

```html
<script>
(function () {
  var script = document.createElement('script');
  script.src = 'https://unpkg.com/web-vitals@3.3.2/dist/web-vitals.iife.js';
  script.onload = function () {
    webVitals.getTTFB(console.log);
  };
  document.head.appendChild(script);
})();
</script>
```

Also, when I look at the code, I do not believe it's possible for the part of the code that calls `performance.now()` to be reached in IE9 because that line is within a conditional that only runs if the browser finds a `navigation` performance entry (which would not be true in IE9). See: https://github.com/GoogleChrome/web-vitals/blob/1d2c191e6763ea3ebeef05e9141847dbce554228/src/onTTFB.ts#L71-L82

So unless I'm missing something then I think the documentation is correct in that the `onTTFB()` function doesn't produce a result in IE9 but it also doesn't error:

> The web-vitals code has been tested and will run without error in all major browsers as well as Internet Explorer back to version 9.

And I think it's fine to continue to make this claim because I do think we want people to be able to run this code anywhere without worry that it will error and potentially break other critical functionality on their site.

**Comment by tunetheweb** [comment] 2023-10-18 18:58
Closing this as no further updates heard back. Feel free to reopen if necessary.

**Closed by tunetheweb** 2023-10-18 18:58 UTC
