### ISSUE TITLE
onTTFB reported without navigation entry after BFCache restore 

### ISSUE THREAD

**Issue by SuperOleg39** [GoogleChrome/web-vitals#313] opened 2023-02-03 09:34 UTC
We use this reciepe - https://github.com/GoogleChrome/web-vitals#onttfb

When page was restored from BFCache, `metric.entries` array is empty and `metric.entries[0].requestStart` will throw error.

What is the correct way to collect TTFB in this case?
Maybe any rework needed in this https://github.com/GoogleChrome/web-vitals/blob/main/src/onTTFB.ts#L95 callback?

**Comment by tunetheweb** [comment] 2023-02-03 09:49
It should report as 0 in this case:

https://github.com/GoogleChrome/web-vitals/blob/0a87ab0897a111d46561578cb1c887981e6353d0/src/onTTFB.ts#L95-L102

I confirmed it does on web.dev:

<img width="870" alt="image" src="https://user-images.githubusercontent.com/10931297/216566911-fb005366-7faf-43b0-a81a-fc901b8861e0.png">

There is an issue (see #275) where TTFB is sometimes not reported when the original nav (that the bfcache restore is restoring too) was the result of a cross origin redirect. In that case we choose not to report a TTFB for the bfcache restore too so it could be you're hitting this issue, in which case you should account for that with optional chaining:

```js
metric.entries[0]?.requestStart
```

Or if you want to report 0 (we choose not to):

```js
metric.entries[0]?.requestStart || 0
```

**Comment by SuperOleg39** [comment] 2023-02-03 10:05
Thank you!

So complete example, if we don't need to report `0`, can use only `metric.value`?

```
import {onTTFB} from 'web-vitals';

onTTFB((metric) => {
  const requestTime = metric.entries[0] ? metric.value - metric.entries[0].requestStart : metric.value;
  console.log('Request time:', requestTime);
});
```

**Comment by SuperOleg39** [comment] 2023-02-03 10:14
Sorry, understand, the main decision is to not report, or report `0`

**Comment by tunetheweb** [comment] 2023-02-03 10:17
Ah yes. In the case of bfcache, as the value is dummied, there is no "entries".

But I don't understand why you are not reporting metric.value every time anyway? Why are you removing the `requestStart` time? That means you are only reporting the actual backend time, but not any connection set up time (DNS, TCP..etc.) nor any redirect time - all of which counts in the [CrUX measured "TTFB"](https://stackoverflow.com/questions/69116839/does-ttfb-include-the-time-for-the-request-that-redirects-to-my-page).

**Comment by SuperOleg39** [comment] 2023-02-03 10:27
> But I don't understand why you are not reporting metric.value every time anyway? 

Good question)

@Zizzamia what do you think about simplify TTFB report in [perfume.js](https://github.com/Zizzamia/perfume.js/blob/master/src/observe.ts#L22)? Or there is some important reason behind this decision?

**Comment by SuperOleg39** [comment] 2023-02-03 10:29
> That means you are only reporting the actual backend time, but not any connection set up time (DNS, TCP..etc.) nor any redirect time

Looks like in `perfume.js` this behaviour is expected for TTFB, because all connection set up time also reported https://zizzamia.github.io/perfume/#/navigation-timing/

**Comment by tunetheweb** [comment] 2023-02-03 10:36
Ah there's so many definitions of TTFB 😁

But for bfcache restores won't they ALL be 0 anyway? So I would guess your decision is whether to just report 0 if it's not defined.

For web-vitals we decided NOT to do that when the original TTFB was 0 - technically this should never happen, so indicates something went wrong (e.g. it was removed for privacy reasons) so rather than report 0, we elected to just not report it (for [the original nav](https://github.com/GoogleChrome/web-vitals/issues/275#issuecomment-1309891031), and [for bfcache restores](https://github.com/GoogleChrome/web-vitals/pull/281#discussion_r1021923946)) to avoid skewing the numbers.

There's argument to still report it for bfcache restores (as it is 0), but we elected not to for consistency.

Either way, I think this is all due to how you're implementing it slightly differently than web-vitals.js (in not using `metric.value` and assuming `metric.entries` should always exist) so think you need to decide how to handle this, rather than change anything in web-vitals. Do you agree and, if so, you OK with me closing this?

**Comment by SuperOleg39** [comment] 2023-02-03 10:44
Thanks for the complete answers, yes looks like everything is fine on the `web-vitals` side and we are free to decide how to handle this cases at our side)

**Closed** 2023-02-03 10:45 UTC
