### ISSUE TITLE
Negative INP values

### ISSUE THREAD

**Issue by lukas1994** [GoogleChrome/web-vitals#272] opened 2022-10-27 02:59 UTC
I just started tracking INP for my app and roughly 10% of the sessions have negative values:
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/6901762/198180455-b0437da9-360f-40f0-9c39-2286a7e739d6.png">

How is that possible?

I also get some extremely large values but that's probably explained by https://github.com/GoogleChrome/web-vitals/issues/229.

**Comment by philipwalton** [comment] 2022-10-27 18:25
Thanks for the report, @lukas1994.

This is indeed strange, and it shouldn't be possible because INP (and all metrics for that matter) are not reported unless their value is >= 0 ([see code](https://github.com/GoogleChrome/web-vitals/blob/v3.0.4/src/lib/bindReporter.ts#L40)).

I was curious to see if any of the sites I track INP on were experiencing this problem, and I did see some negative values as well (though for a significantly smaller % of samples, around 0.01%). However, on other sites I monitor I did not see any negatives values at all.

The main difference (as far as I can tell) between the sites that contain negatives and the sites that do not is whether I'm reporting `metric.value` or `metric.delta`. In the case of reporting `metric.delta` I _am_ seeing some negative values.

INP is the only metric tracked by this library where the value can actually go down over time, since we ignore outliers based on the total number of interactions ([see code](https://github.com/GoogleChrome/web-vitals/blob/v3.0.4/src/onINP.ts#L96-L105)).

The only way I can think of where it would even be *possible* to get a negative value is if two things happen:
1. The page reports an initial INP value that is really high (possibly due to [#229](https://github.com/GoogleChrome/web-vitals/issues/229) as you note)—**and then that report (for whatever reason) is never received by your analytics back end.**
2. The page then reports a new INP value that is lower than the first one, meaning the delta is negative—**and then this report *is* received by your analytics back end.**

Do you think it's possible that that's what happening here? It's hard to imagine that would be the case for 10% of sessions though...

**Comment by lukas1994** [comment] 2022-10-27 20:25
We do use deltas and your explanation makes sense. Definitely quite weird that it happens that much.

Do you think we should instead just use `metric.value` and then take the last one we receive per session?

**Comment by lukas1994** [comment] 2022-10-27 20:44
We're also tracking long event handlers and long tasks and get massive numbers. Is that caused by https://bugs.chromium.org/p/chromium/issues/detail?id=1312568 as well? When do you think this will be fixed? Currently, all our frontend performance numbers are useless because of this bug.

**Comment by philipwalton** [comment] 2022-10-27 23:04
> We do use deltas and your explanation makes sense. Definitely quite weird that it happens that much.

I agree it's weird. Is it possible the method you're using to send data is prone to failure in these cases?

From what I understand, this bug manifests when you open a link in a new tab, which would imply that your page is now in the background. Perhaps it's possible that your code is using `setTimeout()` or `requestAnimationFrame()` or some other method that gets throttled when the page is in a background state?

> Do you think we should instead just use `metric.value` and then take the last one we receive per session?

Yeah, I think overall that's a better approach. The `delta` property was mainly added to make it possible to report on these metrics in Google Analytics since it automatically SUMs any event values, and `delta` was a bit of a hack to make that work.

If you have the ability to always just take the last value received, that's definitely better because it allows you to send other data along with the metric value (e.g. attribution data), and with any non-numeric values you definitely need the ability to just take the last value received.

> We're also tracking long event handlers and long tasks and get massive numbers. Is that caused by https://bugs.chromium.org/p/chromium/issues/detail?id=1312568 as well? When do you think this will be fixed? Currently, all our frontend performance numbers are useless because of this bug.

I think it's very possible that [crbug.com/1312568](https://crbug.com/1312568) is responsible for those massive numbers. I can't speak to timeline, but I know it's a priority for the team. (cc: @mmocny)

**Comment by lukas1994** [comment] 2022-10-30 21:02
Do you know of any easy ways to exclude sessions affected by [crbug.com/1312568](https://crbug.com/1312568)? Is there a way to detect this in the browser before sending the session data to the analytics system? cc @mmocny

**Comment by Anando12** [comment] 2022-10-30 22:57
Success

OPPO F15

**Comment by mmocny** [comment] 2022-11-14 20:56
@lukas1994 Apologies for that bug still lingering.  I have a fix in development just waiting on tests to get written, and keep getting sidetracked.  ETA this week, but then will need to roll into stable over time.

However, I don't see how that issue can affect `long event handlers` and `long tasks`, unless as Philip says you are measuring those in ways where the start and end values include "gaps" of time.  If you are measuring by wrapping callbacks or using the event timing / long tasks apis, those are not related.

**Comment by lukas1994** [comment] 2022-11-16 15:20
@mmocny We're using
```
    new PerformanceObserver(list => {
      // This callback is called whenever a new event
      // (or a series of events) occurs
      for (const entry of list.getEntries()) {
        // Skip `event` events that were cheap
        if (entry.duration < PERFORMANCE_OBSERVER_DURATION_THRESHOLD) {
          continue;
        }
        if (entry.entryType === "event") {
          trackLongEventHandler(
            getSelector((entry as any)?.target),
            entry.duration,
            entry.name,
          );
        } else if (entry.entryType === "longtask") {
          trackLongTask(entry.duration);
        } else {
          console.log(`Unknown entry type: ${entry.entryType}`);
        }
      }
    }).observe({ entryTypes: ["event", "longtask"] })
```

and we're seeing some massive durations for event handlers (like 800k ms). I thought both INP and the PerformanceObserver numbers would be affected by this Chrome bug.

**Comment by mmocny** [comment] 2022-11-16 17:58
Got it.  I misinterpretted "event handlers" and "long tasks" as measuring just main-thread time.  The bug you linked should only affect EventTiming total duration, and only because of off-main-thread timings.

By the way, if you want to filter out entries that have this bug... perhaps there is a way!

You could pick some reasonable threshold specific to presentation delays, which you could tune to your own site data:

```
const MAX_REASONABLE = 2000; // You may want a smaller threshold, but sadly even 2s is not completely unexpected on the web at large

new PerformanceObserver((list) => {
    for (let entry of list.getEntries()) {
        if (!entry.interactionId) continue;
        
        const duration = entry.duration;
        const inputDelay = entry.processingStart - entry.startTime;
        const processingTime = entry.processingEnd - entry.processingStart;
        const presentationDelay = Math.max(0, duration - inputDelay - processingTime);

        if (presentationDelay > MAX_REASONABLE) continue;

        console.log("Event:", duration, inputDelay, processingTime, presentationDelay)
    }
}).observe({ type: 'event', durationThreshold: 16, buffered: true });
```

(There's a chance this isn't perfect, especially in cases where multiple events have high processing times in the same frame, but I think this would be better than ignoring the data completely.)

---

Also FYI:
- [Event Timing `observe()` options support](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/observe#parameters) `durationThreshold`, so you may be able to simplify your "skip"

**Comment by lukas1994** [comment] 2022-11-22 00:29
Thanks! I tried this approach but it doesn't seem to work:

```
duration: 40464
eventKind: pointerdown
interactionId: 8154
presentationDelay: 90.20000004768372
```

I checked out the session in another analytics tool and there's definitely no 40sec main thread block. Do you have any other ideas? If these metrics were reliable they'd be insanely useful :)

**Comment by mmocny** [comment] 2022-11-22 22:21
I assume that it must be input delay, then?

If you could share a trace, or a site that reproduces consistently, that would be very helpful.  I'd love to understand this case further, as it sounds less likely to be the bug you linked.

> If these metrics were reliable they'd be insanely useful :)

Thanks for the feedback!

**Comment by lukas1994** [comment] 2022-12-09 11:27
What do you mean by trace? I'm working on my.causal.app and if you build a large model with complex charts you get these high "long task" values.

I think this also messes up our INP values, e.g. check out the distribution:
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/6901762/206692364-5ba26fef-3618-45d4-a4fd-e122223103a7.png">

**Comment by Anando12** [comment] 2022-12-09 11:40
Success

OPPO F15

**Comment by mmocny** [comment] 2022-12-09 13:50
@lukas1994 By trace I meant like a DevTools performance panel recording (you can save and export those).

Or, if you give me instructions on steps to take on that site to reproduce consistently, I will take a look.

---

The chart you showed looks like you actually have long tasks running very often?  Yes, that would certainly affect INP if it coincides with user interactions (worse if it is caused by the interaction itself).

Are you sure this is a measurement error?

**Comment by Anando12** [comment] 2022-12-09 18:06
Success

OPPO F15

**Comment by lukas1994** [comment] 2022-12-12 00:13
Amazing, thanks for looking into it!

I looked into a few FullStory sessions and actually found a few sessions where the main thread was actually blocked for that amount of time 😢 These should be quite easy to fix though.
Quite a few sessions seem to have a navigation event before the massive INP value is recorded which looks incorrect. If you want to look into this on a quick screenshare I'd be happy to show you some of these sessions (lukas [at] causal.app).

We've looked into webworkers 12 months ago and found that transferring data between the main thread and the worker is quite slow so it ends up blocking the main thread anyway. Might be worth another experiment (potentially using transferrable objects).

**Comment by lukas1994** [comment] 2023-01-05 14:59
Sorry for the delay here and happy new year!

It comes from a MPA document navigation (at least in this one case that I debugged in detail). Your presentation delay solution works well for filtering out unusual long event handlers but the INP code doesn't take it into account.

```
Long event handler: {duration: 48232, eventKind: "click", interactionId: 2819, presentationDelay: 48208}
INP: {value: 48232}
```

This makes our INP metric unusable. Is that something you can fix in this library? If not, we'll probably try to estimate INP values from long task values in our data warehouse.

Happy to do a screen share (I can show you Fullstory recordings and some more detailed data if helpful).

**Comment by lukas1994** [comment] 2023-01-23 23:08
How do y'all feel about filtering events with large presentationDelay when calculating INP? I can submit a PR if that's helpful.

**Comment by tunetheweb** [comment] 2023-10-18 19:10
Doing a clean and up closing this issue as [crbug.com/1312568](https://crbug.com/1312568) is resolved and think we're stepping outside of the scope of the original issue.

**Closed by tunetheweb** 2023-10-18 19:10 UTC
