### ISSUE TITLE
LCP is not friendly with 'carousel' hero image

### ISSUE THREAD

**Issue by skaraman** [GoogleChrome/web-vitals#61] opened 2020-07-07 21:05 UTC
This is a follow up to https://github.com/GoogleChrome/web-vitals/issues/60

On our website (https://www.pogo.com) we have an auto-scrolling hero image, also referred to as a 'carousel' spotlight image. The behavior of this seems to cause a new entry into LCP each time it is changed out before any user interaction. This can lead to a confusing or erroneous LCP response if the page is not interacted with by the user before the first swap occurs. 
<img width="645" alt="Screen Shot 2020-07-07 at 12 54 31 PM" src="https://user-images.githubusercontent.com/2840020/86842857-a2414e80-c05a-11ea-8b71-d86b9bf739a2.png">

Is there any guidance into using LCP with such behavior, or an alternative implementation?

**Comment by philipwalton** [comment] 2020-07-07 22:08
Yeah, unfortunately carousel's are problematic for LCP, and this is something we're actively looking into making better.

Right now we have an experimental implementation in Chrome 85 to _not_ discard elements removed from the DOM, which should help most carousel cases, but we need to gather data on that first to make sure it doesn't have other unintended consequences.

I know "we're working on it" probably isn't the most satisfying answer, but it is the reality of the current situation.

For the perspective of this library, it's working as intended because it's just reporting what the underlying web API is reporting. And any changes we make to the web API to better handle carousel cases should not require any changes to this library.

**Comment by psabharwal123** [comment] 2020-10-16 00:10
hi @philipwalton thanks for the reply, please let us know if there was an update to this issue. LCP is a very important metric since its part of web vitals which will be a ranking factor for SEO in the future, i really hope we won't be penalized for using a carousel because us users seem to love that feature :) For testing purposes you can visit our production site https://www.pogo.com/

**Comment by philipwalton** [comment] 2020-10-22 04:13
The latest update is it's looking like our experimental implementation to not ignore removed DOM elements was successful and will land, so LCP should be much more carousel-friendly in the near future (most likely in Chrome 88).

Since this issue doesn't require any changes to this library, I'm going to close this issue.

**Closed by philipwalton** 2020-10-22 04:13 UTC

**Comment by psabharwal123** [comment] 2020-10-22 19:01
Thanks!
